### ISSUE TITLE
make test not working - 

### ISSUE THREAD

**Issue by Levike34** [casper-ecosystem/hello-world#19]
```
error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /home/levi/.cargo/registry/src/github.com-1ecc6299db9ec823/wait-timeout-0.2.0/src/lib.rs:66:9
   |
66 |         imp::wait_timeout(self, dur)
   |         ^^^ use of undeclared crate or module `imp`
```
I keep getting this error while trying to run 'make test' from this repo.  Any solution to this?

**Comment by Levike34** [comment]
```
error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /home/levi/.cargo/registry/src/github.com-1ecc6299db9ec823/wait-timeout-0.2.0/src/lib.rs:66:9
   |
66 |         imp::wait_timeout(self, dur)
   |         ^^^ use of undeclared crate or module `imp`
```

Still getting this same error.  Can I please get some update or info on this?

**Comment by Levike34** [comment]
This happens when running make test, not just in hello-world but in any other casper repo when I try to run make test

**Comment by gRoussac** [comment]
@Levike34 Hi Thanks for your report and sorry for late reply.

The master branch has been updated and should pass tests accordingly now.
